# Generated by Django 3.2.12 on 2022-03-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multistepform', '0002_auto_20220324_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodataandbiddinginformation',
            old_name='last_name',
            new_name='surname',
        ),
    ]
